name = "sonicjs-app"
main = "src/worker.ts"
compatibility_date = "2026-04-11"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# Cloudflare Workers settings
workers_dev = true

[assets]
binding = "ASSETS"
directory = "./dist"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "sonicjs-db"
database_id = "afd7dca7-7ba2-496a-b1ce-e15ee0cfc9a3"
migrations_dir = "./node_modules/@sonicjs-cms/core/migrations"

# R2 Bucket for media storage
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Production environment
[env.production]
name = "sonicjs-app"
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "topheroes.cwcat.com", custom_domain = true }
    ]

[[env.production.d1_databases]]
binding = "DB"
database_name = "sonicjs-db"
database_id = "afd7dca7-7ba2-496a-b1ce-e15ee0cfc9a3"
migrations_dir = "./node_modules/@sonicjs-cms/core/migrations"

[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media"

# Separate 774 environment
[env.server774]
name = "774topheroes"
routes = [
  { pattern = "774.cwcat.com", custom_domain = true }
]

[env.server774.vars]
ENVIRONMENT = "server774"

[[env.server774.d1_databases]]
binding = "DB"
database_name = "sonicjs-db"
database_id = "d6967cf4-6c6e-4e73-8f87-98b6f1a68c2f"
migrations_dir = "./node_modules/@sonicjs-cms/core/migrations"

[[env.server774.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "774bucket"

# Observability
[observability]
enabled = true
